version: '3.8'

services:
  frontend:
    container_name: front-end 
    build: ..\..\Part1\exercise 1.12\hello-frontend
    depends_on:
      - backend
    ports: 
      - 5000:5000
  backend:
    container_name: back-end 
    build: ..\..\Part1\exercise 1.13\hello-backend
    environment:
      REDIS_HOST: redis 
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    depends_on:
      - redis 
      - postgres
    ports: 
      - 8080:8080
  redis:
    container_name: redis
    image: redis 
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres 
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres